#pragma once

#include "DisplayObject.h"
#include "PlatformTypes.h"

typedef struct ObjectDataTable {
	char header[8];
	ObjectData data[0x6DC];
} ObjectDataTable;

// TODO: Define in PlatformSupport/DataTable.c
extern ROMDATA ObjectDataTable Objects;
#define OBJECTPTR(i) ((const ObjectData*)&Objects.data[(i)])

// TODO: Define all objects here.

#define OBJECTTABLES_SQUAREEXPLOSIONS OBJECTPTR(0x4B)
#define NUMSQUAREEXPLOSIONS 32
#define NUMSQUAREEXPLOSIONTYPES 8

#define OBJECT_NEXTBLOCKLABEL OBJECTPTR(0x151)
#define OBJECT_SCORELABEL OBJECTPTR(0x152)
#define OBJECT_LEVELLABEL OBJECTPTR(0x153)

#define OBJECT_CREDIT OBJECTPTR(0x167)
#define OBJECT_FREE OBJECTPTR(0x168)
#define OBJECT_SERVICE OBJECTPTR(0x169)
#define OBJECT_COINCOLON OBJECTPTR(0x16A)

#define OBJECT_READY OBJECTPTR(0x16B)
#define OBJECT_GO OBJECTPTR(0x16C)

#define OBJECT_PUSH1PSTARTBUTTON OBJECTPTR(0x17B)
#define OBJECT_PUSH2PSTARTBUTTON OBJECTPTR(0x17C)
#define OBJECT_INSERTCOIN OBJECTPTR(0x17F)
#define _0xA6F14 OBJECTPTR(0x181)
#define OBJECT_ADDCOIN OBJECTPTR(0x182)

#define OBJECT_SELECTMODE OBJECTPTR(0x198)

#define OBJECT_CHALLENGE OBJECTPTR(0x199)
#define OBJECTTABLE_YES OBJECTPTR(0x19E)
#define OBJECTTABLE_NO OBJECTPTR(0x1A0)

#define OBJECT_RANKINGTIMECOLON OBJECTPTR(0x1AE)

#define OBJECTTABLE_TIMEDIGITS OBJECTPTR(0x1AF)
#define TIMEDIGIT_WIDTH 16
#define OBJECT_TIMECOLON OBJECTPTR(0x1B9)
#define TIMECOLON_WIDTH 12
#define TIMENUM_WIDTH 28

#define OBJECTTABLE_STATUSDIGITS OBJECTPTR(0x1BA)
#define STATUSDIGIT_WIDTH 8

#define OBJECT_ITEMBARBORDER OBJECTPTR(0x252)
#define OBJECT_ITEMBARBG OBJECTPTR(0x253)
#define OBJECTTABLE_ITEMBARCHUNKS OBJECTPTR(0x254)

#define OBJECT_VERSUSROUNDLIGHT OBJECTPTR(0x264)

#define OBJECTTABLE_CHARS OBJECTPTR(0x279)

#define OBJECTTABLE_LASER OBJECTPTR(0x2FF)
#define OBJECTTABLE_LASERRETICLE OBJECTPTR(0x30F)

#define OBJECTTABLE_ITEMWARNINGTRANSFORM OBJECTPTR(0x35F)
#define OBJECTTABLE_ITEMWARNINGDEATHBLOCK OBJECTPTR(0x3E8)
#define OBJECTTABLE_ITEMWARNINGCOLORBLOCK OBJECTPTR(0x436)
#define OBJECTTABLE_ITEMWARNINGNEGAFIELD OBJECTPTR(0x536)
#define OBJECTTABLE_ITEMWARNINGSHOTGUN OBJECTPTR(0x5B6)

#define OBJECTTABLE_ITEMDESCRIPTIONS OBJECTPTR(0x659)

#define OBJECT_PLEASEWAIT OBJECTPTR(0x66D)
#define OBJECT_NEWCHALLENGER OBJECTPTR(0x66E)

#define OBJECT_SINGLENEXTBLOCKBG OBJECTPTR(0x696)
#define OBJECT_DOUBLESNEXTBLOCKBG OBJECTPTR(0x697)

#define OBJECT_VERSUSWINDIGITS OBJECTPTR(0x699)
#define VERSUSWINDIGIT_WIDTH 8

#define OBJECT_VERSUSWINLABEL OBJECTPTR(0x6A3)

#define OBJECT_SECRETGRADE OBJECTPTR(0x6CC)

#define _0xAAEB0 OBJECTPTR(0x6CE)
#define _0xAAEBC OBJECTPTR(0x6CF)
#define _0xAAEC8 OBJECTPTR(0x6D0)

// TODO: Define OBJECT_MODECODE20G etc. instead of using this. But use
// MODECODES for defining the specific mode code objects.
#define OBJECTTABLE_MODECODES OBJECTPTR(0x6C6)
#define MODECODE_HEIGHT 8

// TODO: Last object.
#define OBJECT_TRYAGAIN OBJECTPTR(0x6DB)