#pragma once

#include "DisplayObject.h"
#include "PlatformTypes.h"

typedef struct ObjectDataTable {
	char header[8];
	ObjectData data[0x6DC];
} ObjectDataTable;

// TODO: Define in PlatformSupport/DataTable.c
extern ROMDATA ObjectDataTable Objects;
#define OBJECTPTR(i) ((ROMDATA ObjectData*)&Objects.data[(i)])

// TODO: Define all objects here.

#define OBJECT_MASTERFIELDBORDER OBJECTPTR(0x4)
#define OBJECT_DOUBLESFIELDBORDER OBJECTPTR(0x5)
#define OBJECT_NORMALFIELDBORDER OBJECTPTR(0x6)

#define OBJECTTABLE_NORMALBLOCKS OBJECTPTR(0x7)
#define OBJECT_HARDBLOCK OBJECTPTR(0x17)
#define OBJECTTABLE_ITEMBLOCKS OBJECTPTR(0x18)
#define OBJECTTABLES_BLOCKEXPLOSIONS OBJECTPTR(0x4B)
#define NUMBLOCKEXPLOSIONS 32
#define NUMBLOCKEXPLOSIONTYPES 8

#define OBJECT_NEXTBLOCKLABEL OBJECTPTR(0x151)
#define OBJECT_SCORELABEL OBJECTPTR(0x152)
#define OBJECT_LEVELLABEL OBJECTPTR(0x153)

#define OBJECT_CREDIT OBJECTPTR(0x167)
#define OBJECT_FREE OBJECTPTR(0x168)
#define OBJECT_SERVICE OBJECTPTR(0x169)
#define OBJECT_COINCOLON OBJECTPTR(0x16A)

#define OBJECT_READY OBJECTPTR(0x16B)
#define OBJECT_GO OBJECTPTR(0x16C)

#define OBJECT_PUSH1PSTARTBUTTON OBJECTPTR(0x17B)
#define OBJECT_PUSH2PSTARTBUTTON OBJECTPTR(0x17C)
#define OBJECT_INSERTCOIN OBJECTPTR(0x17F)
#define _0xA6F14 OBJECTPTR(0x181)
#define OBJECT_ADDCOIN OBJECTPTR(0x182)

#define OBJECT_SELECTMODE OBJECTPTR(0x198)

#define OBJECT_CHALLENGE OBJECTPTR(0x199)
#define OBJECTTABLE_YES OBJECTPTR(0x19E)
#define OBJECTTABLE_NO OBJECTPTR(0x1A0)

#define OBJECTTABLE_RANKINGDIGITS OBJECTPTR(0x1A4) 
#define OBJECT_RANKINGTIMECOLON OBJECTPTR(0x1AE)

#define OBJECTTABLE_TIMEDIGITS OBJECTPTR(0x1AF)
#define TIMEDIGIT_WIDTH 16
#define OBJECT_TIMECOLON OBJECTPTR(0x1B9)
#define TIMECOLON_WIDTH 12
#define TIMENUM_WIDTH 28

#define OBJECTTABLE_STATUSDIGITS OBJECTPTR(0x1BA)
#define STATUSDIGIT_WIDTH 8

#define OBJECT_SINGLEFIELDBG OBJECTPTR(0x1D8)
#define OBJECT_DOUBLESFIELDBG OBJECTPTR(0x1D9)

#define OBJECTTABLE_RANKINGCHARS OBJECTPTR(0x1DA)

#define OBJECTTABLE_MEDALS OBJECTPTR(0x23D)

#define OBJECT_ITEMBARBORDER OBJECTPTR(0x252)
#define OBJECT_ITEMBARBG OBJECTPTR(0x253)
#define OBJECTTABLE_ITEMBARCHUNKS OBJECTPTR(0x254)

#define OBJECT_VERSUSROUNDLIGHT OBJECTPTR(0x264)

#define OBJECTTABLE_CHARS OBJECTPTR(0x279)

#define OBJECTTABLE_LASER OBJECTPTR(0x2FF)
#define OBJECTTABLE_LASERRETICLE OBJECTPTR(0x30F)
#define OBJECTTABLE_ITEMWARNINGROLLROLL OBJECTPTR(0x31F)
#define OBJECTTABLE_ITEMWARNINGTRANSFORM OBJECTPTR(0x35F)
#define OBJECTTABLE_ROWDEL OBJECTPTR(0x39F)
#define OBJECTTABLE_ITEMWARNINGHARDBLOCK OBJECTPTR(0x3A7)
#define OBJECT_COLUMNMARKER OBJECTPTR(0x3E7)
#define OBJECTTABLE_ITEMWARNINGDEATHBLOCK OBJECTPTR(0x3E8)
#define OBJECTTABLE_ITEMWARNINGCOLORBLOCK OBJECTPTR(0x436)
#define OBJECTTABLE_ITEMWARNINGDARKBLOCK OBJECTPTR(0x476)
#define OBJECTTABLE_ITEMWARNINGEXCHGFIELD OBJECTPTR(0x4B6)
#define OBJECTTABLE_ITEMWARNINGMIRRORBLOCK OBJECTPTR(0x4F6)
#define OBJECTTABLE_ITEMWARNINGNEGAFIELD OBJECTPTR(0x536)
#define OBJECTTABLE_ITEMWARNINGSHOTGUN OBJECTPTR(0x5B6)
#define OBJECTTABLE_ITEMWARNINGXRAY OBJECTPTR(0x5F6)
#define OBJECTTABLE_ITEMDESCRIPTIONS OBJECTPTR(0x659)

#define OBJECT_PLEASEWAIT OBJECTPTR(0x66D)
#define OBJECTTABLE_NEWCHALLENGER OBJECTPTR(0x66E)

#define OBJECT_SINGLENEXTBLOCKBG OBJECTPTR(0x696)
#define OBJECT_DOUBLESNEXTBLOCKBG OBJECTPTR(0x697)

#define OBJECT_GRANDMASTERCONGRATULATIONS OBJECTPTR(0x698)

#define OBJECT_VERSUSWINDIGITS OBJECTPTR(0x699)
#define VERSUSWINDIGIT_WIDTH 8
#define OBJECT_VERSUSWINLABEL OBJECTPTR(0x6A3)

#define OBJECTTABLE_FIREWORKS OBJECTPTR(0x6A6)

// TODO: Define OBJECT_MODECODE20G etc. instead of using this. But use
// MODECODES for defining the specific mode code objects.
#define OBJECTTABLE_MODECODES OBJECTPTR(0x6C6)
#define MODECODE_HEIGHT 8

#define OBJECT_SECRETGRADE OBJECTPTR(0x6CC)

#define OBJECT_BRAVO OBJECTPTR(0x6CD)

#define _0xAAEB0 OBJECTPTR(0x6CE)
#define _0xAAEBC OBJECTPTR(0x6CF)
#define _0xAAEC8 OBJECTPTR(0x6D0)

#define OBJECT_RETRYFORGRANDMASTER OBJECTPTR(0x6DB)