#pragma once

// TODO: Define constants for all palette numbers here.
typedef enum PalNum {
	PALNUM_SMALLTEXT = 0u, // TODO: PALNUM_STATUSTEXT?
	PALNUM_ITEMDESCRIPTION = 4u,
	PALNUM_10 = 10,
	PALNUM_SYSTEMTEXT = 81u,
	PALNUM_SYSTEMSPECIALTEXT = 82u,
	PALNUM_TEXTOVERLAYBG = 157u,
	PALNUM_PALCYCLETEXT = 159u,
	PALNUM_NEXTBLOCKBG = 208u
} PalNum;
