#pragma once

#include "Video/PalNum.h"

// TODO: Define constants for all palette numbers here.
#define PALNUM_OBJECT UINT8_C(0)
#define PALNUM_ITEMDESCRIPTION UINT8_C(4)
#define PALNUM_CHECKSUMNG UINT8_C(10)
#define PALNUM_15 UINT8_C(15)
#define PALNUM_14 UINT8_C(14)
#define PALNUM_ALPHA UINT8_C(148)
#define PALNUM_TEXTOVERLAYBG UINT8_C(157)
#define PALNUM_PALCYCLETEXT UINT8_C(159)
#define PALNUM_ITEMBLOCKEXPLOSION UINT8_C(188)
#define PALNUM_NEXTBLOCKBG UINT8_C(208)
