#include "Game/HwData.h"

// TODO: Consider removing this.
ROMDATA void* ROM[0x100000 / sizeof(void*)];

RAMDATA void* WORKRAM[0x100000 / sizeof(void*)];
RAMDATA uint8_t INPUTS[NUMINPUTS];
RAMDATA uint8_t EEPROM[4];
RAMDATA uint8_t SOUNDCTRL[8];
RAMDATA uint32_t GRAPHICSRAM[0x10000 / sizeof(uint32_t)];
RAMDATA Color PALRAM[NUMPALS * NUMPALCOLORS_4BPP];
RAMDATA uint16_t SCALERAM[0x100];
RAMDATA uint8_t VIDEOCTRL;
RAMDATA uint8_t IRQCTRL[4];
RAMDATA uint8_t VIDEOREGS[0x20];
